### ISSUE TITLE
OK button missing in preview dialog

### ISSUE THREAD

**Issue by sascha-andres** [mProjectsCode/obsidian-media-db-plugin#94] opened 2023-05-25 03:52 UTC
I wanted to add another movie and I can't click on OK to create the file in the preview dialog:

![image](https://github.com/mProjectsCode/obsidian-media-db-plugin/assets/3052075/3d8ffda0-35e8-4bc1-8029-5c346dbf98ca)

What I tried:
- restarted Obsidian
- Changed the theme

Is there any work around?

**Comment by mbryantms** [comment] 2023-05-26 13:41
I am experiencing the same issue. This happens for all media types and doesn't matter what content is in the template. I can't create an entry for anything.

**Comment by mProjectsCode** [comment] 2023-05-26 14:15
I am currently on vacation. I will take a look at it when I am back.

**Comment by discipleofzen** [comment] 2023-05-29 16:21
OK button is present on Android, but not on desktop. Functionality is given for Android version.

**Comment by mProjectsCode** [comment] 2023-05-29 17:06
I cant reproduce the issue with obsidian `1.3.4` and plugin version `0.5.1`.

**Comment by discipleofzen** [comment] 2023-05-29 18:20
Obsidian 1.3.4 and Plugin 0.5.1 checked right now, at least movies cannot be added as no OK button is present. Other media not checked. Checked 2023-05-19 20:20 Berlin time.

**Comment by mProjectsCode** [comment] 2023-05-29 18:26
which API are you using?

**Comment by discipleofzen** [comment] 2023-05-29 21:12
If you could give more details on what to look up, I will do so.

**Comment by sascha-andres** [comment] 2023-05-30 03:39
> which API are you using?
> 

I am trying to use OMDb

**Comment by mProjectsCode** [comment] 2023-05-30 06:57
> If you could give more details on what to look up, I will do so. 

You could open the developer console and look for any errors that appear there.

**Comment by discipleofzen** [comment] 2023-05-30 12:36
Well, let's see if this works. 

![API](https://github.com/mProjectsCode/obsidian-media-db-plugin/assets/20475015/9a9ea53e-4359-4c8a-8fb5-96afffd9d699)

**Comment by mProjectsCode** [comment] 2023-05-30 14:37
The first error appeared on my end too and it should be fixed with the commit I did yesterday (but i couldn't test it yet), but considering that the buttons are there on my end, it's likely not the root cause.
Can you try disableing metadata menu? it seems to be doing something weird to the preview modal.

**Comment by mbryantms** [comment] 2023-05-30 14:52
Similar for mine: 
![image](https://github.com/mProjectsCode/obsidian-media-db-plugin/assets/2883226/1556be98-47cf-402e-8c33-25890f9d9ef0)

**Comment by mProjectsCode** [comment] 2023-05-30 15:01
are you using templates that include dataview querries? If so could you send one of those to me?

**Comment by nikitakuma** [comment] 2023-05-30 15:03
I had the same problem and checked the console, it was mentioning Supercharged Links every time I tried a MediaDB entry. The OK button came back once I turned off Supercharged Links. Tested this on a few different items and different templates and the OK button came back every time I turned that plugin off

**Comment by sascha-andres** [comment] 2023-05-30 15:04
Yes, I do. Here is the movie tmeplate:

```
[[11.00 Index|Movie list]]

`$= '![Image|360](' + dv.current().image + ')'`

# `$= dv.current().title`

>>>dataviewjs
if (dv.current().watched) {
	dv.paragraph(`> [!SUCCESS] \`INPUT[toggle:watched]\` watched \n last watched on ${dv.current().lastWatched || '---'}`);
} else {
	dv.paragraph(`> [!WARNING] \`INPUT[toggle:watched]\` not yet watched`);
}
>>>

**Rating**:  `INPUT[slider(addLabels, minValue(0), maxValue(10)):personalRating]` (`$= dv.current().personalRating` out of 10)

**Genres**:
>>>dataviewjs
dv.current().genres.length === 0 ? dv.span(' - none') : dv.list(dv.current().genres)
>>>

>>>dataviewjs
if (!dv.current().released) {
	dv.span('**Not released** The movie is not yet released.')
}
>>>

**Type**: `$= dv.current().type` <br />
**Online Rating**: `$= dv.current().onlineRating` <br />
**Duration**:  `$= dv.current().duration` <br />
**Premiered**: `$= dv.current().premiere` <br />
**Producer**: `$= dv.current().producer` <br />
```

Replaces triple tick with triple gt

**Comment by mbryantms** [comment] 2023-05-30 15:05
I have tried with this template and it doesn't work. A movieTemplate I have without a dataview query does allow the Ok button to appear with no issue. Here's the gameTemplate I took which I pulled from the forum or SirVB's or somewhere like that:


```
gameTemplate

not yet played


Genres:
$= dv.current().genres.length === 0 ? ' - none' : dv.list(dv.current().genres)

Dataview (for inline JS query 'dv.current().genres.length === 0 ? ' - none' : dv.list(dv.current().genres)'): TypeError: Cannot read properties of undefined (reading 'length')
Not released The game is not yet released.
Type:
Online Rating:
Release Date:
```

**Comment by mProjectsCode** [comment] 2023-05-30 15:25
I think I identified the issue. Other plugins are throwing errors in the preview and causing the render process to halt, sometimes before the buttons have been rendered. I guess I will just ignore the errors for now so that the rendering can continue.

**Comment by mProjectsCode** [comment] 2023-05-30 15:35
a new release that hopefully fixes the issue is deployed

**Comment by mbryantms** [comment] 2023-05-30 15:43
Applied the update in Obsidian. I can confirm it works for all my media
types now. Appreciate the help and amazing plugin!

**Comment by nikitakuma** [comment] 2023-05-30 15:45
Works now with all my plugins, thank you!

**Comment by mProjectsCode** [comment] 2023-05-30 16:07
great, then I will close this issue

**Closed by mProjectsCode** 2023-05-30 16:07 UTC
Labels: bug

**Comment by sascha-andres** [comment] 2023-05-31 03:50
I can also confirm. Great job!
