### ISSUE TITLE
Searching for movie "Dune" gives me an API key error

### ISSUE THREAD

**Issue by technoplayer** [mProjectsCode/obsidian-media-db-plugin#97] opened 2023-07-04 20:30 UTC
-   [x ] The Plugin is up to date
-   [ x] Obsidian is up to date

**Describe the bug**
Typing the word Dune or dune for an OMDB search yields an API key error, so far every other movie word or title I have tried has worked without issue.

**To Reproduce**

1. Initiate Media DB Advanced Search.
2. Toggle OMDdAPI to on.
3. In the box titled Search by title, enter the word Dune (or dune).
4. Message appears, saying "Error: MDB | Authentication for OMDbAPI failed. Check the API key.".

**Expected behavior**
To be presented with a list of movies with Dune in the title.

**Screenshots**

**Occurs on**

-   [ ] Windows
-   [ ] macOS
-   [x ] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.5.2

**Additional context**
<img width="316" alt="Screenshot_20230704_212702" src="https://github.com/mProjectsCode/obsidian-media-db-plugin/assets/22190657/a9a22919-6359-4cc4-9c26-4657ea429c43">

**Comment by fischgeek** [comment] 2023-07-07 14:19
Same here, but for anything I search.

**Comment by pligrim** [comment] 2023-07-21 16:10
Did you click on the link in the email to activate your key and try the test usl query that was in the activation email?

**Comment by mProjectsCode** [comment] 2023-08-24 08:57
Can't reproduce, so i will close this issue

**Comment by careilly** [comment] 2023-08-25 12:02
Getting the same problem on MacOS, newly installed plugin, all up to date, using latest insider release.

I have activated the key and test url works fine.

**Comment by careilly** [comment] 2023-08-25 12:15
See below. "Babylon 5" is the only case I make it break on! Which was the first thing I searched for after I installed the plugin.

plugin:obsidian-media-db-plugin:5280 Error: MDB | Authentication for OMDbAPI failed. Check the API key.
    at OMDbAPI.eval (plugin:obsidian-media-db-plugin:3813:15)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-media-db-plugin:50:24)

eval | @ | plugin:obsidian-media-db-plugin:5280
-- | -- | --
  | rejected | @ | plugin:obsidian-media-db-plugin:57
  | Promise.then (async) |   |  
  | step | @ | plugin:obsidian-media-db-plugin:62
  | fulfilled | @ | plugin:obsidian-media-db-plugin:50
  | Promise.then (async) |   |  
  | step | @ | plugin:obsidian-media-db-plugin:62
  | eval | @ | plugin:obsidian-media-db-plugin:63
  | __async | @ | plugin:obsidian-media-db-plugin:47
  | openSearchModal | @ | plugin:obsidian-media-db-plugin:5263
  | eval | @ | plugin:obsidian-media-db-plugin:5575
  | eval | @ | plugin:obsidian-media-db-plugin:63
  | __async | @ | plugin:obsidian-media-db-plugin:47
  | createEntryWithSearchModal | @ | plugin:obsidian-media-db-plugin:5573
  | callback | @ | plugin:obsidian-media-db-plugin:5497
  | i_ | @ | app.js:1
  | t.onChooseItem | @ | app.js:1
  | t.onChooseSuggestion | @ | app.js:1
  | t.selectSuggestion | @ | app.js:1
  | e.useSelectedItem | @ | app.js:1
  | e.onSuggestionClick | @ | app.js:1
  | s | @ | enhance.js:1

**Comment by careilly** [comment] 2023-08-25 12:34
Does the code cache anything? Maybe the query is being cached the other side, I called it before the API key was confirmed and it's cached the error?

**Comment by mProjectsCode** [comment] 2023-08-25 14:17
This could be the case. If so, there is nothing i can do about it.

**Comment by mProjectsCode** [comment] 2024-04-11 20:12
I will close this, as i was never able to reproduce the issue. In any case, it seems to be more an issue with OMDB and not the plugin.

**Closed by mProjectsCode** 2024-04-11 20:12 UTC
Labels: bug, help wanted
